version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: development
    volumes:
      - "./api:/var/www"
    depends_on:
      - postgres
    environment:
      - API_PORT=${API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - ${API_PORT}:${API_PORT}

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: postgres -p ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
